### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nabidam** [mideaconu/face-recognition#2]
Hi, I'm working on a face recognition method, and need the FERET dataset, I already emailed to their official, and request the dataset, but they didn't respond me, so I ask you if you could help me by somehow sending to me your image files. Any help would be appreciated.
Thanks.

**Comment by mideaconu** [comment]
Hi @nabidam, I just double-checked the release agreement and unfortunately they prohibit further distribution of the database. I remember my request taking a full working day to be replied to, so I would suggest giving it a couple more days. They are researchers so they might be away for a conference or have a busier week, but there shouldn't be any issues granting you access to the image set. If you work on a similar project and need help with e.g. preprocessing the face images drop me a message, I might be more helpful with that.

**Comment by nabidam** [comment]
I thank you very much for your respond. I guess I should wait much longer, and hope they accept my request.
